version: '3.8'
services:
  node:
    build: ./node
    environment:
      - NODE_ENV=development
      - NODEJS_PORT=3001
    volumes:
      - "./node:/home/node/app/"
      - "be-node-modules:/home/node/app/node_modules/"
    ports:
      - "3001:3001"
  react:
    build: ./react
    volumes:
      - "build:/home/node/app/build"
      - "./react:/home/node/app/"
      - "fe-node-modules:/home/node/app/node_modules/"
    ports:
      - "3000:3000"
    links:
      - node
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true


volumes:
  build:
  be-node-modules:
  fe-node-modules: